server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /seckill

spring:
  application:
    name: seckill-project
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: your_password
    # 数据库连接池，当前 hikari 是性能最优的
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间
      idle-timeout: 60000
      # 最大连接数
      maximum-poool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存货时间，0 表示永久存货
      max-lifetime: 60000
      # 连接超时时间
      connection-timeout: 30000
      # 心跳测试语句
      connection-test-query: SELECT 1
  
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  devtools:
    restart:
      enabled: true

#Mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.seckill.entity

logging:
  level:
    com.seckill: debug
    org.springframework: info