server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /seckill

spring:
  application:
    name: seckill-project
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: your_password
  
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.seckill: debug
    org.springframework: info